config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :task_delete
  get '/tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  get '/tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container my-5">
      <div class="row m-5">
        <div class="col p-5">

    <%= yield %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul class="list-inline border-bottom-secondary ">
  <% @tasks.each do |task| %>
  <li>
    <%= check_box_tag(task.title, value = "1", checked = task.completed) %>
    <%= link_to task.title, task_path(task) %>
    <%= link_to task_delete_path(task), method: :delete, data: {confirm:"Delete #{task.title}?"} do %>
    <i class="far fa-trash-alt"></i><% end %>
  </li>
  <% end %>
</ul>
<p class="py-3"><%= link_to "+ Add a new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<ul>
  <li><%= @task.details %></li>
  <li><%= @task.completed %></li>
</ul>
<%= link_to "Back to list", tasks_path %>
<p><%= link_to "Edit this task", task_edit_path %></p>